Updated README
GlobalWebIndex/cmd-extra pull request #3
Opened 2018-09-03 07:46 UTC by kraklin

2018-09-03 20:01 UTC, rofrol approved these changes

2018-09-04 05:56 UTC, turboMaCk commented on README.md
> +        = DoNothing
this is usually called `NoOp`

2018-09-04 05:56 UTC, turboMaCk commented on README.md
> +                Cmd.Extra.pure
this is not right. pure expects model as and argument

2018-09-04 05:57 UTC, turboMaCk requested changes
see comments

2018-09-04 06:25 UTC, kraklin commented on README.md
> +                Cmd.Extra.pure
🤦‍♂️

2018-09-04 06:35 UTC, turboMaCk commented on README.md
> +This package adds some functions that helps you with constructing of `Cmd msg` from given `msg` and theirs manipulation.
in fact manipulation is not about Cmd but about pair `(a, Cmd b)`

2018-09-04 07:11 UTC, turboMaCk commented on README.md
> +This package adds some functions that helps you with constructing of `(model, Cmd msg)` pair from given `model` and `msg` and theirs manipulation.
this is also not acurate. perform attempt and maybe are not working with pair.

there are 2 things that this package provides:

1. constructors for Cmds
2. way to compose (model, Cmd msg) pairs in pipelines.

2018-09-04 08:52 UTC, turboMaCk commented on README.md
> +This package can help you with construction of `Cmd msg` and composition of pair `(model, Cmd msg)` that can be used to streamline your flow of actions in `update`.
great!!!

2018-09-04 08:52 UTC, turboMaCk approved these changes
LGTM

2018-09-04 08:53 UTC, merged

2018-09-04 08:54 UTC, kraklin commented
Can you publish it @turboMaCk ? I'm not sure if I'm able to do that.